project_id = "fojsmhovtpnacxxahauf"

[functions.upload-media]
verify_jwt = false

[functions.setup-storage]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-phone-otp]
verify_jwt = false
